CREATE TABLE IF NOT EXISTS public."Cardapios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Mistura" text COLLATE pg_catalog."default" NOT NULL,
    "Guarnicao" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Cardapios" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Cardapios"
    OWNER to postgres;

INSERT INTO public."Cardapios" ("Mistura", "Guarnicao") VALUES ('Isca de Carne, Calabresa Acebolada, Linguiça Tosacana Frita, Parmegiana de Frango, Filé de Frango Empanado, Ovo Frito', 'Isca de Carne, Calabresa Acebolada, Linguiça Tosacana Frita, Parmegiana de Frango, Filé de Frango Empanado, Ovo Frito');

CREATE TABLE IF NOT EXISTS public."PedidoEntregas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Telefone" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "NomeRua" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "NumeroRua" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Bairro" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Cidade" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PedidoEntregas" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."PedidoEntregas"
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public."PedidoRetiradas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Telefone" character varying(70) COLLATE pg_catalog."default" NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PedidoRetiradas" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."PedidoRetiradas"
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public."Pedidos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Valor" numeric NOT NULL,
    "Tamanho" text COLLATE pg_catalog."default" NOT NULL,
    "Guarnicao" text[][] COLLATE pg_catalog."default" NOT NULL,
    "Mistura" text[][] COLLATE pg_catalog."default" NOT NULL,
    "PedidoEntregaId" integer,
    "PedidoRetiradaId" integer,
    "Status" status_pedido DEFAULT 'Novos'::status_pedido,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pedidos_PedidoEntregas_PedidoEntregaId" FOREIGN KEY ("PedidoEntregaId")
        REFERENCES public."PedidoEntregas" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FK_Pedidos_PedidoRetiradas_PedidoRetiradaId" FOREIGN KEY ("PedidoRetiradaId")
        REFERENCES public."PedidoRetiradas" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Pedidos"
    OWNER to postgres;

-- Index: public.IX_Pedidos_PedidoEntregaId
CREATE INDEX IF NOT EXISTS "IX_Pedidos_PedidoEntregaId"
    ON public."Pedidos" USING btree
    ("""PedidoEntregaId""" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: public.IX_Pedidos_PedidoRetiradaId
CREATE INDEX IF NOT EXISTS "IX_Pedidos_PedidoRetiradaId"
    ON public."Pedidos" USING btree
    ("""PedidoRetiradaId""" ASC NULLS LAST)
    TABLESPACE pg_default;